#!/usr/bin/env bash
# World wide web

config () {
    cmd=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $cmd" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
  config "$1" "www"
  config "$1" "lb-01"
  config "$1" "web-01"
  config "$1" "web-02"
elif [ "$#" == 2 ]; then
  config "$1" "$2"
fi
