#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy
config=\
"
frontend  frontend
        bind *:80
        mode http
        default_backend backend
backend backend
        balance roundrobin
        server 63210-web-01 100.25.19.204:80 check
        server 63210-web-02 54.157.159.85:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
