#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely unless process beheaded

file="/var/run/myscript.pid"
echo "$$" > "$file"

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM
	trap 'rm "$file" && exit' SIGQUIT
done
