#!/usr/bin/env bash
# Display a list of currently running processes
# Show all processes for all users,
# including those who might not have a TTY
# Show process hierarchy
# Show processes that whose name contain the word "bash"

ps -aux | grep "bash"
