#!/usr/bin/env bash
# Configure a Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "localhost	127.0.0.2\nfacebook.com	8.8.8.8" > ~/hosts.new
cat ~/hosts.new > /etc/hosts
