#!/usr/bin/env bash
# Configure a Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
printf "127.0.0.2	localhost\n8.8.8.8	facebook.com" > ~/hosts.new
cat ~/hosts.new > /etc/hosts
